//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace schedule_bot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("schedule_bot.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string AddVacation {
            get {
                return ResourceManager.GetString("AddVacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string FullScheduling {
            get {
                return ResourceManager.GetString("FullScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string GreetingMessage {
            get {
                return ResourceManager.GetString("GreetingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string SetupNotifications {
            get {
                return ResourceManager.GetString("SetupNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string ShowList {
            get {
                return ResourceManager.GetString("ShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string TodayScheduling {
            get {
                return ResourceManager.GetString("TodayScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string TomorrowScheduling {
            get {
                return ResourceManager.GetString("TomorrowScheduling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string UpdateTaskStatus {
            get {
                return ResourceManager.GetString("UpdateTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string UserIsNotAdmin {
            get {
                return ResourceManager.GetString("UserIsNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;empty&gt;.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
